### ISSUE TITLE
Dispose in SnappyReader

### ISSUE THREAD

**Issue by vl85** [aloneguid/IronSnappy#5]
There are
`Snappy.BytePool.Return(_ibuf);
Snappy.BytePool.Return(_obuf);`
in Dispose in SnappyWriter.
But no 
`Snappy.BytePool.Return(_buf);
Snappy.BytePool.Return(_decoded);`
or Dispose in SnappyReader.

I don't see a reason why would it be correct.

Does it affect Parquet.NET?

**Comment by vl85** [comment]
Parquet.NET doesn't use streaming. Instead it says that streaming in IronSnappy is in work in progress state and implements its own shortcut to buffer methods.

**Comment by aloneguid** [comment]
It's not quite related to IronSnappy, however streaming in parquet.net is not required as it works with loads of tiny buffers, so in theory it's better not to stream snappy at all for performance reasons.
