### ISSUE TITLE
Roundtrip fails for Snappy.OpenWriter -> Snappy.OpenReader?

### ISSUE THREAD

**Issue by rodo-r2r** [aloneguid/IronSnappy#7]
Hi!

I was looking to replace our existing snappy lib (Snappy.NET) with one that supports .net core.

This project looks really nice, and could be exactly what I was looking for ... however I can't get files to Snappy.OpenReader/OpenWriter to roundtrip, or load from other snappy writers (either Snappy.NET, or https://github.com/robertvazan/snappy-command-line which I used for testing).

I wrote a test to confirm the issue:
```
   public class RoundtripTest
   {
      [Fact]
      public void RoundtripSimple()
      {
         // var memStream = new MemoryStream();
         string path = "temp.snappy";
         string text = "foo bar baz";

         using(FileStream file = File.OpenWrite(path))
         using(Stream zip = Snappy.OpenWriter(file))
         using(StreamWriter writer = new StreamWriter(zip))
         {
            writer.Write(text);
         }

         using(FileStream file = File.OpenRead(path))
         using(Stream zip = Snappy.OpenReader(file))
         using(StreamReader reader = new StreamReader(zip))
         {
            string result = reader.ReadToEnd();
            Assert.Equal(text, result);
         }
      }
   }
```

Is this failure expected?

It looks like there are a few issues with the golang -> c# translation and the current tests don't hit the Reader/Writer path at all.

I'm half way through writing a PR that seems to fix some of the issues, would you like me to send a PR when it's ready?

Also, unrelated to this bug, do you have any perf numbers on this lib?
Curious how it performs (in ballpark numbers) compared to native snappy.

**Comment by rodo-r2r** [comment]
I sent through the PR above, let me know if it needs additional changes.

Also, I'm not super familiar with either golang or spans, so potentially messed something up :-)

**Comment by kirchsth** [comment]
Can we close it?
(Based on release details I think it is part of nuget v. 1.3.0)

BR Helmut
